dist: trusty
language: ruby
jdk: openjdk8

rvm:
  - jruby-9.1.9.0

script:
  - bundle exec rspec spec

deploy:
  provider: rubygems
  api_key:
    secure: PNXWdzg0XT5EG/JzTGp/TdXKD3HkHFoSzjqjnRhsWIn18rYNnrGOzPv696C0Yxi4xw2S3Unwr+sC1KzHlzB1UxAzU8jM6UldDxxB6BAVspNCOGAOYQ7tA8C4CPA3jT23/YWXVy4CZ1mNmrgy5F50wZTliyx81ApQtW5uHDTeR9XAkUjqnH8vpexu5e1/OQlo/gtYMmKQPw01Oc2cLDlQ4Kcs/vKW8iEip0huebSCmJ9pp0TGjUAghM/L78zgnUQd4paSsJpvkCtcVtF/SZcxsCWxRsyoxemaY/XezIUzMzgXLg3X1ekGDWCDNDTJAK4quMBNsn6BDj0gzyEzwwBP+aNzApKBJXHsgSRV7+6cYU8tGQLVroTILcbCBz5T72FM4C7ALXDAzPL8fWQ6KbDD3qmRZ80rJJ1hEloW9Lipe+SwRvR+iDt+n0VxqAvKG9x4KqakGsvHMZ4joo9h29cZhjfeubW2uSQUj4RBmngN/nLvKKI+Vh4L9l4qBYGoe7REEfDq6TJr3EycBcAKR/EZ9OGU8H/1gSvzkUHYCvePuL8Jso+hGp9Numx6sgXMj7jXiKVMtkr/bXWTt6LvHoGlIoiFKTlRqNr03obQAk48U28E3pPUc72X3mQtjZdsZ/Pe3jk1nz7viJFalKLwWV7wLmislINQldON8WJP7JaYYeU=
  gem: logstash-output-honeycomb_json_batch
  on:
    tags: true
